name: Deploy to Cloud Run Job

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker to push to Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudruntest/drive-sheet-job:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudruntest/drive-sheet-job:latest

      - name: Deploy to Cloud Run Job
        run: |
          gcloud run jobs update drive-sheet-job \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudruntest/drive-sheet-job:latest \
            --region=us-central1 || \
          gcloud run jobs create drive-sheet-job \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudruntest/drive-sheet-job:latest \
            --region=us-central1
